project:
  type: website

website:
  title: "Beth — Notes & Analyses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Notes
        menu:
          - notes/2025-08-09_Test.qmd

format:
  html:
    theme:
      light: default
      dark: slate
    toc: true
    code-copy: true
